# 전역 설정
global:
  imageRegistry: "862016452072.dkr.ecr.ap-northeast-2.amazonaws.com"  # 서울 리전 ECR
  namespace: app-services
  serviceAccount: kubox-secrets-sa

# 서비스별 설정
services:
  userService:
    name: user-svc
    serviceName: user-svc
    image:
      repository: kubox
      tag: user-service-v6
    port: 8080
    env:
      DB_NAME: "user_db"
    secrets:
      - kubox-common-secret
      - kubox-bootpay-secret
    keda:
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilization: 80
      
  productService:
    name: product-svc
    serviceName: product-svc
    image:
      repository: kubox
      tag: product-service-v5
    port: 8081
    env:
      DB_NAME: "product_db"
    secrets:
      - kubox-common-secret
    keda:
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilization: 80
      
  cartService:
    name: cart-svc
    serviceName: cart-svc
    image:
      repository: kubox
      tag: cart-service-v8
    port: 8084
    env:
      DB_NAME: "cart_db"
    secrets:
      - kubox-common-secret
    keda:
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilization: 80
      
  orderService:
    name: order-svc
    serviceName: order-svc
    image:
      repository: kubox
      tag: order-service-v8
    port: 8082
    env:
      DB_NAME: "order_db"
    secrets:
      - kubox-common-secret
    keda:
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilization: 80
      
  paymentService:
    name: payment-svc
    serviceName: payment-svc
    image:
      repository: kubox
      tag: payment-service-v6
    port: 8083
    env:
      DB_NAME: "payment_db"
    secrets:
      - kubox-common-secret
      - kubox-bootpay-secret
    keda:
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilization: 80

# 리소스 설정
resources:
  requests:
    cpu: "50m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

# 헬스체크 설정
healthCheck:
  paths: 
    base: "/actuator/health"
    startup: "/actuator/health/liveness"
    liveness: "/actuator/health/liveness"
    readiness: "/actuator/health/readiness"
  startupProbe:
    periodSeconds: 10
    failureThreshold: 60
    timeoutSeconds: 5
    initialDelaySeconds: 120
  livenessProbe:
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    initialDelaySeconds: 180
  readinessProbe:
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
    initialDelaySeconds: 150

# Secrets Store CSI 설정
secretsStore:
  enabled: true
  secretProviderClass: kubox-secrets
  mountPath: "/mnt/secrets"

# Istio 설정
istio:
  enabled: true
  gateway:
    name: kubox-gateway
    namespace: default
    hosts:
      - "*"
    tls:
      credentialName: kubox-tls-secret
  virtualService:
    name: kubox-virtual-service
    namespace: default
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: "5xx,reset,connect-failure,refused-stream"
    routes:
      - path: "/api/auth"
        service: userService
      - path: "/api/users"
        service: userService
      - path: "/api/products"
        service: productService
      - path: "/api/cart"
        service: cartService
      - path: "/api/orders"
        service: orderService
      - path: "/api/payment"
        service: paymentService
